dist: trusty
sudo: required
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
services:
- docker
env:
  global:
  - secure: V/xd024R566kbfggoCyxWsKYpxPNa3k94uBR4HwaPtKk84GJaAKfl8kJJfBb3oXgyNxqj/q59mH/KmSmW5fEK3tr1ldstNeEAIMW3o2sNJua3MWM12Lxm3VhdAJvBbKSWs7tiTX8/7pdi74ejy3c+TfZ1qnggDtjIyADazQjTUFe5fei49YqNcfRZxB/5PXLugr/ZSF3uL88berdY/otiCglqFeiG4IJBZVG1WYjUb1LaaEGY7Xt4sXRk4LBBeLdqjhoeEWv4cM9hcPBnNJqL+zvCqKvcBPZ4+9fbUivFShwbP+LvmnuBlyPoge3P1UzP8dJEyeCGKmLIROYz7wOy6gByxoAEbUvJZuTmcRlfxcoLWB4h4xfblh0TqGshdE2HjbdqJUQLxoFoeDNdfIUQSelz+dBGqCi1gtM2zJ1m3pG3GoKYW/KVytMzEx+FIhrdSeBejt0QGBqtCQtyJOrqGOlcGvJIK8Y0F4Y8hJ3O8e7jgUvp20nzSu4Fcgefi8SdfqIRcF62L7dNOCmvbJD0CEJX88Qi2L5V9q6jrQKbMR8uo0JcRs9HlBUm1i18Ks3iKHjwZswETyyqTVQ3KlxtQLfLaWiqm67X/koGR6jmlc4l9r+UqkitY1LyKhQT8DmaAleYcbFXqgm3+j7WFeL7fbg3mbs4uCrje9CtuS6M+w=
  - secure: k1YKkVK3vFzfPVPCVZ4utM6GeAAXAKPgMwnGgrjTn5Lx7Rg0SP9yCD82LraLrY2KXe4niao16+XuUPrEQMeaRKETDUnVFHYgThP1cgC9vJj/f8C1TBJRYJnP+pYceC+xLkl+u8BL31cqwejQDyUqtJ8OWACg6tfK9iRr6Qx/AXm4Hnx5ib0rn1y5/mTfRRL0NdH29wbosgPyhMQMrd7vpu+hZFb6oO0F0ZrfK7TnKuvO8aY1rOJRQmOHEA/qr+81oeXO6vClunE2W55aBRttV7jfwDoRpSPoHoJFunQXhefsJ5OrYolAlaXZsoGwrdnm85NjlT0wrIu+w6zoxW/vQ0+SOHZxxPDcYtXaMqu2C7AuVIGAd5rz3NczqdfGhFjnzhiqTuanNI19cMZ5Wa4KzgR/Wxy0xwMwUgGqzi/47o8hNYtOjNs0JS5dGA/YLOiMzaKk/rUTeEft/w/rn/vLf0hyDouIl107+ullw5lgDpba8Uv584Yk7jrnQG5SOxBkxKwx78tyokXFSLWJmjF9oj3ZXqbfqxfjCSwnP0HFpsZ8V197101K2u3yn9plNKeWT9JjrG087ArPq2ycYboeUxM6c/kd4QsE+8WnK/BwcpMQaLsdTLE5oZTtGOSKVYZZWyrI8ip1bLvgsw7MsldPzEFlhZjJudvVUR0X4qmYtU4=
  - secure: Wt8YVkUrvdlLbVY4ogaKO0dK3vBOT6EREIaPCJrTzf7U/QAqLlq5JCJEFQe6HeIzleXeL8HRaaVLkdKE2rYDAxOehcJiwbICk9/6QsPu21av489d3sBW057NJsENc6nf0+rsicWZOSBfIdCG2AHoqXfpJDh5q2gPqQVA+f6vuBWLoo2jRi0RUUhM0UaWdDdjFShExI7WY/pn2XVNLG8UfOjZHLf3hDDTPB/V3VJm+s9b1cVX6Ql8AIV9ZsImtG/laBNtKvhKCccSQcg9SFR+PeQzsryzWRCMZ30Xrduyah4O4AXEXUiaeeWlNeK7lRn2oiV/Pmd6Onv9UtTnmyn+QeW/2hAH60d7EHmuOM5RsLe0HC/glOA7Vql9KmEwQFRiHUqaHhKSgpEkCZ5FX9xi1OgwN/OyEeBL3fQEg6b6qeHnfE2NM1qT2+A2gWJmta8dENawU4S/1Sq64R7j80mfBDMXoGrz33YqcaYyWDusYzPVRaB60vymNfM/NVp1hkYSDb5OcqvnXflsDQNk7fINaNQOMAY9IXp0TjOsokmqLXv40V3vbCrBmSDOVDNWeKmh2bjRn62OyHT05JyJB3o2zL30T0n9idtKZ1BjAZIH3L24YirAsJKkSQJHgp9kYVrDPDb1MHXJb5V7OxMaZoqPMgUZYGZc7QJ6aDcDRjteVxs=
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean install jacoco:report coveralls:report -Pcoverage surefire-report:report-only
  && python html2text.py target/site/surefire-report.html
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  mvn sonar:sonar -Psonar -Dsonar.organization=database-rider -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=${SONAR_KEY} ; fi ;
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  cd rider-core && mvn -q cukedoctor:execute scm-publish:publish-scm -Pdocs ; fi ;
- if [[ $TRAVIS_COMMIT_MESSAGE == *"prepare release"* ]]; then mvn -q cukedoctor:execute
  scm-publish:publish-scm -Pdocs -Prelease ; fi ;
after_script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  cd ../ && mvn clean package deploy --settings settings.xml -DskipTests=true ; fi;
