sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean install jacoco:report coveralls:report -Pcoverage surefire-report:report-only
- cd rider-core && mvn -q cukedoctor:execute scm-publish:publish-scm -Pdocs
after_script:
- cd .. && python html2text.py target/site/surefire-report.html
env:
  global:
  - secure: NeGB3Dm+jI71QZnHrDB+5mbrKdnYAEzA724AzxKEx+ZQnjik8C9HGNc6M3LzED2gxPba5f06DjJAK55TP1dw/TVsvDC/8PvDtlpReucvCdvA0RSwFtCJlf95Itsz1CAdVZTzIsnKjdMT5CR5TNFyrPZ5NY0WNJiBPUcHfjrOD4vzYgvVYKAyXADxaPIrwUfOokcpbNupSBpFRM+N6/X3CcG8fwMyepGhBugsSaOvg/7pe1nduao4KthnTsP4urmTYZF9LUmrZyw/X5HlkEZWOUqi9q5e/HTTwHzwmYN+6g7ZPCh8KOUQDyNo+RbBip1LwiycutnxMtXPN7nNg7S4RUBTiG1Wf/F6fL6muyqIyBOxtgjNWn+OncTwRVY80MI5P3L1bJBXtJ9nCZ8sQRdieDuLO4Ss6E1a6hsovKcEtxWWCuRfRNrjhIOU5wCHXyKP6X0MloL9+avsSYSsluXXmUM2S6/MjsoojZ5UFSQs9LAXwV8GTQejMb9yNBs4KKDjVrtIeN7w6w6JLUASIZZkXktGmT/KJwapv4z53iSAXlSJ0/44c76PV7T3gBW/DG/KWj1NlWrhd8J01fwHZvQuxq3xeOPQq2TAJUq4apJ4KuYaINGOpndTnpwPNRoP7UVBj176Atc4+NrpNKCdIg0dBWVUpqVkbTkJM+c77b/SBws=
  - secure: FDiyW6XID+f2qOU8kFey9ckZXf5/jNYZirpAYJBGgsFxyMdb9BEoqcF+nOj40tOzO6aqGmd8Zd8yEDsE2dtiqtZArj3XYRp4etNNmjS+cDfl7PVjPuTgcdsxrmfjDpRFrYnPy5Re1ZTCnvvdBzPcIXpbM6hVA/0A3BLwhvzavHSK4S+S/RuOHpu4L6kvIEnJ+TEDIy4taleGU2GFv8Zv/d4uydgbKQaXiqyyLJ2vWCW7RwPmx4se/2k3cMiN+USs257Zj7GOEo9M8vuhy5iH5FQfJPxp831iRlhOISNY/EqXQ+10EmJB/gGkHWUwUNVOljcGRZdGk6CS/Lg8eUDYxteCVvhnoH+E10mwGMqBwk+OthJcDyjZiTrK2SmX+ESeTAFDH4qBuBBUNymbx0Q27wJJKtvA3p8R5s6aIFW3Jpp5+I34iCp5drzrk0/HE4QscIYAGH13lnluPJl+Xb7A7uO4VU8HbDZrwjxzxphYqiiRxsi9kX75bvf3OYRVID3YWQHu/urT6+MqG8E/In5GpZlm214jXCJCDe8OGHq2cLS5IdG14GFjfaM+DkpX3QpLRIUDz35n9HLlVNukgXTvOjg03DQrx978bbwj8pvc/YAWRJaLGHOEWrj/tGStn6BUCLpaFv0/6c+IU0/TgBsmbJ+lP9ZfEJGH+Vm5Vfc/VMQ=
